# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: 64.227.100.181
        username: root
        password: ${{secrets.PASSWORD}}
        port: 22
        script: 
         cd ~/backend-bantucarioksigen
         git pull origin master
         git status
         npm install
         pm2 restart backend-bantucarioksigen
